CREATE TABLE auth_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL,
    email VARCHAR(320) NOT NULL,
    normalized_email VARCHAR(320) NOT NULL,
    /*
     * Trạng thái do ứng dụng quản lý.
     * Giá trị hợp lệ được khai báo trong Java enum.
     */
    status VARCHAR(20) NOT NULL,
    email_verified_at TIMESTAMPTZ,
    last_login_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT uk_auth_users_public_id UNIQUE (public_id),
    CONSTRAINT uk_auth_users_normalized_email
        UNIQUE (normalized_email)
);
