/*
 * Authentication data is intentionally isolated from recruitment data.
 * Raw credentials and bearer tokens must never be stored in this database.
 */

ALTER TABLE auth_users
    ADD COLUMN deleted_at TIMESTAMPTZ;

UPDATE auth_users
SET deleted_at = updated_at
WHERE status = 'DELETED' AND deleted_at IS NULL;

ALTER TABLE auth_users
    ADD CONSTRAINT ck_auth_users_email_not_blank
        CHECK (char_length(btrim(email)) > 0),
    ADD CONSTRAINT ck_auth_users_normalized_email_not_blank
        CHECK (char_length(btrim(normalized_email)) > 0),
    ADD CONSTRAINT ck_auth_users_status
        CHECK (status IN ('PENDING', 'ACTIVE', 'SUSPENDED', 'DELETED')),
    ADD CONSTRAINT ck_auth_users_version
        CHECK (version >= 0),
    ADD CONSTRAINT ck_auth_users_timestamps
        CHECK (updated_at >= created_at),
    ADD CONSTRAINT ck_auth_users_deleted_at
        CHECK (
            (status = 'DELETED' AND deleted_at IS NOT NULL)
            OR (status <> 'DELETED' AND deleted_at IS NULL)
        );

CREATE TABLE password_credentials (
    user_id BIGINT PRIMARY KEY,
    password_hash TEXT NOT NULL,
    hash_algorithm VARCHAR(32) NOT NULL,
    password_changed_at TIMESTAMPTZ NOT NULL,
    failed_attempt_count INTEGER NOT NULL DEFAULT 0,
    last_failed_at TIMESTAMPTZ,
    locked_until TIMESTAMPTZ,
    must_change_password BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT fk_password_credentials_user
        FOREIGN KEY (user_id) REFERENCES auth_users (id) ON DELETE CASCADE,
    CONSTRAINT ck_password_credentials_hash_not_blank
        CHECK (char_length(password_hash) >= 20),
    CONSTRAINT ck_password_credentials_algorithm_not_blank
        CHECK (char_length(btrim(hash_algorithm)) > 0),
    CONSTRAINT ck_password_credentials_failed_attempt_count
        CHECK (failed_attempt_count >= 0),
    CONSTRAINT ck_password_credentials_version
        CHECK (version >= 0),
    CONSTRAINT ck_password_credentials_timestamps
        CHECK (
            password_changed_at >= created_at
            AND updated_at >= created_at
            AND (last_failed_at IS NULL OR last_failed_at >= created_at)
        )
);

COMMENT ON COLUMN password_credentials.password_hash IS
    'Self-describing Argon2id/bcrypt/PBKDF2 hash; never a plaintext or reversible password.';

CREATE TABLE roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    code VARCHAR(64) NOT NULL,
    name VARCHAR(120) NOT NULL,
    description TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    system_role BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT uk_roles_code UNIQUE (code),
    CONSTRAINT ck_roles_code_format
        CHECK (code ~ '^[A-Z][A-Z0-9_]{1,63}$'),
    CONSTRAINT ck_roles_name_not_blank
        CHECK (char_length(btrim(name)) > 0),
    CONSTRAINT ck_roles_status
        CHECK (status IN ('ACTIVE', 'INACTIVE')),
    CONSTRAINT ck_roles_version
        CHECK (version >= 0),
    CONSTRAINT ck_roles_timestamps
        CHECK (updated_at >= created_at)
);

CREATE TABLE permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    code VARCHAR(100) NOT NULL,
    description TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_permissions_code UNIQUE (code),
    CONSTRAINT ck_permissions_code_format
        CHECK (code ~ '^[a-z][a-z0-9_.:-]{2,99}$'),
    CONSTRAINT ck_permissions_description_not_blank
        CHECK (char_length(btrim(description)) > 0)
);

CREATE TABLE user_roles (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    assigned_by_user_id BIGINT,
    assigned_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_user_roles PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user_roles_user
        FOREIGN KEY (user_id) REFERENCES auth_users (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_roles_role
        FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE RESTRICT,
    CONSTRAINT fk_user_roles_assigned_by
        FOREIGN KEY (assigned_by_user_id) REFERENCES auth_users (id) ON DELETE SET NULL
);

CREATE INDEX ix_user_roles_role_user
    ON user_roles (role_id, user_id);

CREATE TABLE role_permissions (
    role_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    granted_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_role_permissions PRIMARY KEY (role_id, permission_id),
    CONSTRAINT fk_role_permissions_role
        FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE,
    CONSTRAINT fk_role_permissions_permission
        FOREIGN KEY (permission_id) REFERENCES permissions (id) ON DELETE CASCADE
);

CREATE INDEX ix_role_permissions_permission_role
    ON role_permissions (permission_id, role_id);

/*
 * A session is the refresh-token family. Each rotation creates a new immutable
 * token row in refresh_tokens. Reuse of a consumed token revokes the session.
 */
CREATE TABLE auth_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    client_type VARCHAR(30) NOT NULL,
    device_name VARCHAR(120),
    user_agent VARCHAR(512),
    created_ip VARCHAR(45),
    last_seen_ip VARCHAR(45),
    authenticated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_seen_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    idle_expires_at TIMESTAMPTZ NOT NULL,
    absolute_expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,
    revoke_reason VARCHAR(80),
    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT fk_auth_sessions_user
        FOREIGN KEY (user_id) REFERENCES auth_users (id) ON DELETE CASCADE,
    CONSTRAINT ck_auth_sessions_client_type
        CHECK (client_type IN ('WEB', 'MOBILE', 'SERVICE')),
    CONSTRAINT ck_auth_sessions_expiry
        CHECK (
            last_seen_at >= authenticated_at
            AND idle_expires_at > authenticated_at
            AND absolute_expires_at >= idle_expires_at
            AND (revoked_at IS NULL OR revoked_at >= authenticated_at)
        ),
    CONSTRAINT ck_auth_sessions_revoke_reason
        CHECK (
            (revoked_at IS NULL AND revoke_reason IS NULL)
            OR (revoked_at IS NOT NULL AND revoke_reason IS NOT NULL
                AND char_length(btrim(revoke_reason)) > 0)
        ),
    CONSTRAINT ck_auth_sessions_version
        CHECK (version >= 0)
);

CREATE INDEX ix_auth_sessions_active_user
    ON auth_sessions (user_id, absolute_expires_at)
    WHERE revoked_at IS NULL;

CREATE INDEX ix_auth_sessions_expiry
    ON auth_sessions (absolute_expires_at);

CREATE TABLE refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    session_id BIGINT NOT NULL,
    token_hash CHAR(64) NOT NULL,
    parent_token_id BIGINT,
    replaced_by_token_id BIGINT,
    issued_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMPTZ NOT NULL,
    used_at TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ,
    revoke_reason VARCHAR(80),

    CONSTRAINT uk_refresh_tokens_hash UNIQUE (token_hash),
    CONSTRAINT uq_refresh_tokens_session_id UNIQUE (session_id, id),
    CONSTRAINT fk_refresh_tokens_session
        FOREIGN KEY (session_id) REFERENCES auth_sessions (id) ON DELETE CASCADE,
    CONSTRAINT fk_refresh_tokens_parent
        FOREIGN KEY (session_id, parent_token_id)
        REFERENCES refresh_tokens (session_id, id) ON DELETE RESTRICT,
    CONSTRAINT fk_refresh_tokens_replacement
        FOREIGN KEY (session_id, replaced_by_token_id)
        REFERENCES refresh_tokens (session_id, id) ON DELETE RESTRICT,
    CONSTRAINT ck_refresh_tokens_sha256
        CHECK (token_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_refresh_tokens_expiry
        CHECK (
            expires_at > issued_at
            AND (used_at IS NULL OR used_at >= issued_at)
            AND (revoked_at IS NULL OR revoked_at >= issued_at)
        ),
    CONSTRAINT ck_refresh_tokens_replacement
        CHECK (replaced_by_token_id IS NULL OR replaced_by_token_id <> id),
    CONSTRAINT ck_refresh_tokens_revoke_reason
        CHECK (
            (revoked_at IS NULL AND revoke_reason IS NULL)
            OR (revoked_at IS NOT NULL AND revoke_reason IS NOT NULL
                AND char_length(btrim(revoke_reason)) > 0)
        )
);

CREATE INDEX ix_refresh_tokens_session_issued
    ON refresh_tokens (session_id, issued_at DESC);

CREATE INDEX ix_refresh_tokens_expiry
    ON refresh_tokens (expires_at);

CREATE TABLE one_time_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    token_type VARCHAR(30) NOT NULL,
    token_hash CHAR(64) NOT NULL,
    requested_ip VARCHAR(45),
    attempt_count INTEGER NOT NULL DEFAULT 0,
    expires_at TIMESTAMPTZ NOT NULL,
    consumed_at TIMESTAMPTZ,
    invalidated_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_one_time_tokens_hash UNIQUE (token_hash),
    CONSTRAINT fk_one_time_tokens_user
        FOREIGN KEY (user_id) REFERENCES auth_users (id) ON DELETE CASCADE,
    CONSTRAINT ck_one_time_tokens_type
        CHECK (token_type IN ('EMAIL_VERIFICATION', 'PASSWORD_RESET', 'EMAIL_CHANGE')),
    CONSTRAINT ck_one_time_tokens_sha256
        CHECK (token_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_one_time_tokens_attempt_count
        CHECK (attempt_count >= 0),
    CONSTRAINT ck_one_time_tokens_expiry
        CHECK (
            expires_at > created_at
            AND (consumed_at IS NULL OR consumed_at >= created_at)
            AND (invalidated_at IS NULL OR invalidated_at >= created_at)
        ),
    CONSTRAINT ck_one_time_tokens_terminal_state
        CHECK (consumed_at IS NULL OR invalidated_at IS NULL)
);

CREATE UNIQUE INDEX uk_one_time_tokens_active_user_type
    ON one_time_tokens (user_id, token_type)
    WHERE consumed_at IS NULL AND invalidated_at IS NULL;

CREATE INDEX ix_one_time_tokens_expiry
    ON one_time_tokens (expires_at);

CREATE TABLE auth_audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    actor_user_id BIGINT,
    target_user_id BIGINT,
    session_id BIGINT,
    action VARCHAR(100) NOT NULL,
    outcome VARCHAR(20) NOT NULL,
    resource_type VARCHAR(80),
    resource_id UUID,
    reason_code VARCHAR(80),
    correlation_id UUID NOT NULL,
    ip_address VARCHAR(45),
    metadata JSONB NOT NULL DEFAULT '{}'::JSONB,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_auth_audit_logs_actor
        FOREIGN KEY (actor_user_id) REFERENCES auth_users (id) ON DELETE SET NULL,
    CONSTRAINT fk_auth_audit_logs_target
        FOREIGN KEY (target_user_id) REFERENCES auth_users (id) ON DELETE SET NULL,
    CONSTRAINT fk_auth_audit_logs_session
        FOREIGN KEY (session_id) REFERENCES auth_sessions (id) ON DELETE SET NULL,
    CONSTRAINT ck_auth_audit_logs_action_not_blank
        CHECK (char_length(btrim(action)) > 0),
    CONSTRAINT ck_auth_audit_logs_outcome
        CHECK (outcome IN ('SUCCEEDED', 'FAILED', 'DENIED')),
    CONSTRAINT ck_auth_audit_logs_metadata_object
        CHECK (jsonb_typeof(metadata) = 'object')
);

CREATE INDEX ix_auth_audit_logs_actor_occurred
    ON auth_audit_logs (actor_user_id, occurred_at DESC);

CREATE INDEX ix_auth_audit_logs_target_occurred
    ON auth_audit_logs (target_user_id, occurred_at DESC);

CREATE INDEX ix_auth_audit_logs_correlation
    ON auth_audit_logs (correlation_id);

CREATE TABLE outbox_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    aggregate_type VARCHAR(80) NOT NULL,
    aggregate_id UUID NOT NULL,
    aggregate_version BIGINT NOT NULL,
    event_type VARCHAR(120) NOT NULL,
    schema_version SMALLINT NOT NULL,
    idempotency_key VARCHAR(200) NOT NULL,
    correlation_id UUID NOT NULL,
    causation_id UUID,
    payload JSONB NOT NULL,
    headers JSONB NOT NULL DEFAULT '{}'::JSONB,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    available_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    published_at TIMESTAMPTZ,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    locked_by VARCHAR(120),
    locked_at TIMESTAMPTZ,
    last_error_code VARCHAR(80),
    last_error_at TIMESTAMPTZ,

    CONSTRAINT uk_outbox_events_idempotency_key UNIQUE (idempotency_key),
    CONSTRAINT ck_outbox_events_aggregate_type_not_blank
        CHECK (char_length(btrim(aggregate_type)) > 0),
    CONSTRAINT ck_outbox_events_aggregate_version
        CHECK (aggregate_version >= 0),
    CONSTRAINT ck_outbox_events_event_type_not_blank
        CHECK (char_length(btrim(event_type)) > 0),
    CONSTRAINT ck_outbox_events_schema_version
        CHECK (schema_version > 0),
    CONSTRAINT ck_outbox_events_payload_object
        CHECK (jsonb_typeof(payload) = 'object'),
    CONSTRAINT ck_outbox_events_headers_object
        CHECK (jsonb_typeof(headers) = 'object'),
    CONSTRAINT ck_outbox_events_attempt_count
        CHECK (attempt_count >= 0),
    CONSTRAINT ck_outbox_events_timestamps
        CHECK (
            available_at >= occurred_at
            AND (published_at IS NULL OR published_at >= occurred_at)
            AND (
                (locked_at IS NULL AND locked_by IS NULL)
                OR (locked_at IS NOT NULL AND locked_by IS NOT NULL)
            )
            AND (
                (last_error_at IS NULL AND last_error_code IS NULL)
                OR (last_error_at IS NOT NULL AND last_error_code IS NOT NULL)
            )
        )
);

CREATE INDEX ix_outbox_events_pending
    ON outbox_events (available_at, occurred_at)
    WHERE published_at IS NULL;

CREATE INDEX ix_outbox_events_aggregate
    ON outbox_events (aggregate_type, aggregate_id, aggregate_version);

