/*
 * Supports replay-safe commands such as registration. response_body may hold
 * only a safe resource representation; authentication and one-time tokens are
 * never persisted here.
 */
CREATE TABLE idempotency_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    key_hash CHAR(64) NOT NULL,
    operation VARCHAR(100) NOT NULL,
    request_hash BYTEA NOT NULL,
    state VARCHAR(20) NOT NULL,
    resource_type VARCHAR(80),
    resource_id UUID,
    response_status INTEGER,
    response_body JSONB,
    locked_until TIMESTAMPTZ,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT uk_idempotency_records_operation_key UNIQUE (operation, key_hash),
    CONSTRAINT ck_idempotency_records_key_hash
        CHECK (key_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_idempotency_records_operation_not_blank
        CHECK (char_length(btrim(operation)) > 0),
    CONSTRAINT ck_idempotency_records_request_digest
        CHECK (octet_length(request_hash) = 32),
    CONSTRAINT ck_idempotency_records_state
        CHECK (state IN ('PROCESSING', 'COMPLETED', 'FAILED')),
    CONSTRAINT ck_idempotency_records_state_shape
        CHECK (
            (state = 'PROCESSING'
                AND locked_until IS NOT NULL
                AND response_status IS NULL
                AND response_body IS NULL
                AND resource_type IS NULL
                AND resource_id IS NULL)
            OR (state IN ('COMPLETED', 'FAILED')
                AND locked_until IS NULL
                AND response_status IS NOT NULL)
        ),
    CONSTRAINT ck_idempotency_records_response_status
        CHECK (response_status IS NULL OR response_status BETWEEN 100 AND 599),
    CONSTRAINT ck_idempotency_records_response_body
        CHECK (response_body IS NULL OR jsonb_typeof(response_body) = 'object'),
    CONSTRAINT ck_idempotency_records_expiry
        CHECK (
            expires_at > created_at
            AND updated_at >= created_at
            AND (locked_until IS NULL OR locked_until >= created_at)
        ),
    CONSTRAINT ck_idempotency_records_version
        CHECK (version >= 0)
);

CREATE INDEX ix_idempotency_records_expiry
    ON idempotency_records (expires_at);

ALTER TABLE auth_sessions
    ADD CONSTRAINT ck_auth_sessions_idle_after_last_seen
        CHECK (idle_expires_at >= last_seen_at);
