ALTER TABLE applications
    ADD COLUMN consent_accepted BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN consent_policy_version VARCHAR(80) NOT NULL DEFAULT 'cv-sharing-v1';

CREATE TABLE candidate_consents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL,
    candidate_user_id UUID NOT NULL,
    consent_type VARCHAR(40) NOT NULL,
    policy_version VARCHAR(80) NOT NULL,
    accepted_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    revoked_at TIMESTAMPTZ,
    CONSTRAINT uk_candidate_consents_public_id UNIQUE (public_id),
    CONSTRAINT uk_candidate_consents_version UNIQUE (candidate_user_id, consent_type, policy_version),
    CONSTRAINT ck_candidate_consents_type CHECK (consent_type IN ('CV_SHARING')),
    CONSTRAINT ck_candidate_consents_lifecycle CHECK (revoked_at IS NULL OR revoked_at >= accepted_at)
);

CREATE TABLE application_cv_access_grants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL,
    application_id BIGINT NOT NULL,
    cv_version_id BIGINT NOT NULL,
    company_id BIGINT NOT NULL,
    consent_id BIGINT NOT NULL,
    granted_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    revoked_at TIMESTAMPTZ,
    CONSTRAINT uk_application_cv_access_grants_public_id UNIQUE (public_id),
    CONSTRAINT uk_application_cv_access_grants_application UNIQUE (application_id),
    CONSTRAINT fk_application_grants_application FOREIGN KEY (application_id) REFERENCES applications (id) ON DELETE RESTRICT,
    CONSTRAINT fk_application_grants_cv_version FOREIGN KEY (cv_version_id) REFERENCES cv_versions (id) ON DELETE RESTRICT,
    CONSTRAINT fk_application_grants_company FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE RESTRICT,
    CONSTRAINT fk_application_grants_consent FOREIGN KEY (consent_id) REFERENCES candidate_consents (id) ON DELETE RESTRICT,
    CONSTRAINT ck_application_grants_lifecycle CHECK (revoked_at IS NULL OR revoked_at >= granted_at)
);
