CREATE TABLE company_invitations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    company_id BIGINT NOT NULL,
    email VARCHAR(320) NOT NULL,
    normalized_email VARCHAR(320) NOT NULL,
    role VARCHAR(30) NOT NULL,
    token_hash CHAR(64) NOT NULL UNIQUE,
    invited_by_user_id UUID NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    accepted_by_user_id UUID,
    accepted_at TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_company_invitations_company FOREIGN KEY (company_id)
        REFERENCES companies (id) ON DELETE RESTRICT,
    CONSTRAINT ck_company_invitations_email CHECK (
        char_length(btrim(email)) > 3
        AND normalized_email = lower(btrim(email))
        AND position('@' IN normalized_email) > 1
    ),
    CONSTRAINT ck_company_invitations_role CHECK (role IN ('COMPANY_ADMIN', 'RECRUITER', 'VIEWER')),
    CONSTRAINT ck_company_invitations_token_hash CHECK (token_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_company_invitations_lifecycle CHECK (
        ((accepted_by_user_id IS NULL AND accepted_at IS NULL)
            OR (accepted_by_user_id IS NOT NULL AND accepted_at IS NOT NULL))
        AND NOT (accepted_at IS NOT NULL AND revoked_at IS NOT NULL)
    ),
    CONSTRAINT ck_company_invitations_version CHECK (version >= 0),
    CONSTRAINT ck_company_invitations_timestamps CHECK (
        expires_at > created_at
        AND updated_at >= created_at
        AND (accepted_at IS NULL OR accepted_at >= created_at)
        AND (revoked_at IS NULL OR revoked_at >= created_at)
    )
);

CREATE UNIQUE INDEX uk_company_invitations_active_email
    ON company_invitations (company_id, normalized_email)
    WHERE accepted_at IS NULL AND revoked_at IS NULL;

CREATE INDEX ix_company_invitations_company_created
    ON company_invitations (company_id, created_at DESC);

