CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    user_id UUID NOT NULL,
    type VARCHAR(50) NOT NULL,
    title VARCHAR(180) NOT NULL,
    message VARCHAR(1000) NOT NULL,
    link_url VARCHAR(500),
    deduplication_key VARCHAR(240) NOT NULL UNIQUE,
    read_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_notifications_content CHECK (
        char_length(btrim(type)) > 0
        AND char_length(btrim(title)) > 0
        AND char_length(btrim(message)) > 0
        AND char_length(btrim(deduplication_key)) > 0
    ),
    CONSTRAINT ck_notifications_lifecycle CHECK (read_at IS NULL OR read_at >= created_at),
    CONSTRAINT ck_notifications_version CHECK (version >= 0)
);

CREATE INDEX ix_notifications_user_created
    ON notifications (user_id, created_at DESC);

CREATE INDEX ix_notifications_user_unread
    ON notifications (user_id, created_at DESC)
    WHERE read_at IS NULL;

