CREATE TABLE candidate_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL,
    user_id UUID NOT NULL,
    display_name VARCHAR(120) NOT NULL,
    headline VARCHAR(200),
    location_text VARCHAR(160),
    visibility VARCHAR(30) NOT NULL DEFAULT 'APPLICATION_ONLY',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT uk_candidate_profiles_public_id UNIQUE (public_id),
    CONSTRAINT uk_candidate_profiles_user_id UNIQUE (user_id),
    CONSTRAINT ck_candidate_profiles_display_name CHECK (char_length(btrim(display_name)) > 0),
    CONSTRAINT ck_candidate_profiles_visibility CHECK (visibility IN ('PRIVATE', 'APPLICATION_ONLY')),
    CONSTRAINT ck_candidate_profiles_version CHECK (version >= 0),
    CONSTRAINT ck_candidate_profiles_timestamps CHECK (updated_at >= created_at)
);
