CREATE TABLE cvs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL,
    candidate_user_id UUID NOT NULL,
    title VARCHAR(160) NOT NULL,
    active_version_id BIGINT,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    archived_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ,
    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT uk_cvs_public_id UNIQUE (public_id),
    CONSTRAINT uk_cvs_owner_id UNIQUE (candidate_user_id, id),
    CONSTRAINT ck_cvs_title CHECK (char_length(btrim(title)) > 0),
    CONSTRAINT ck_cvs_status CHECK (status IN ('ACTIVE', 'ARCHIVED', 'DELETED')),
    CONSTRAINT ck_cvs_lifecycle CHECK (
        updated_at >= created_at
        AND (
            (status = 'ACTIVE' AND archived_at IS NULL AND deleted_at IS NULL)
            OR (status = 'ARCHIVED' AND archived_at IS NOT NULL AND deleted_at IS NULL)
            OR (status = 'DELETED' AND deleted_at IS NOT NULL)
        )
    ),
    CONSTRAINT ck_cvs_version CHECK (version >= 0)
);

CREATE TABLE cv_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL,
    cv_id BIGINT NOT NULL,
    version_number INTEGER NOT NULL,
    object_bucket VARCHAR(120) NOT NULL,
    object_key VARCHAR(600) NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    mime_type VARCHAR(100) NOT NULL,
    size_bytes BIGINT NOT NULL,
    sha256 CHAR(64) NOT NULL,
    language_hint VARCHAR(16),
    processing_status VARCHAR(30) NOT NULL DEFAULT 'UPLOADED',
    failure_code VARCHAR(80),
    confirmed_at TIMESTAMPTZ,
    created_by_user_id UUID NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT uk_cv_versions_public_id UNIQUE (public_id),
    CONSTRAINT uk_cv_versions_cv_number UNIQUE (cv_id, version_number),
    CONSTRAINT uk_cv_versions_cv_id UNIQUE (cv_id, id),
    CONSTRAINT uk_cv_versions_object UNIQUE (object_bucket, object_key),
    CONSTRAINT fk_cv_versions_cv FOREIGN KEY (cv_id) REFERENCES cvs (id) ON DELETE RESTRICT,
    CONSTRAINT ck_cv_versions_number CHECK (version_number > 0),
    CONSTRAINT ck_cv_versions_object CHECK (
        char_length(btrim(object_bucket)) > 0 AND char_length(btrim(object_key)) > 0
    ),
    CONSTRAINT ck_cv_versions_pdf CHECK (mime_type = 'application/pdf'),
    CONSTRAINT ck_cv_versions_size CHECK (size_bytes > 0 AND size_bytes <= 10485760),
    CONSTRAINT ck_cv_versions_sha256 CHECK (sha256 ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_cv_versions_status CHECK (
        processing_status IN (
            'UPLOADED', 'QUEUED', 'PROCESSING', 'PARSED', 'NEEDS_REVIEW',
            'CONFIRMED', 'REJECTED', 'FAILED', 'SUPERSEDED', 'DELETED'
        )
    ),
    CONSTRAINT ck_cv_versions_result CHECK (
        (processing_status NOT IN ('REJECTED', 'FAILED') OR failure_code IS NOT NULL)
        AND (processing_status <> 'CONFIRMED' OR confirmed_at IS NOT NULL)
    ),
    CONSTRAINT ck_cv_versions_version CHECK (version >= 0),
    CONSTRAINT ck_cv_versions_timestamps CHECK (updated_at >= created_at)
);

ALTER TABLE cvs
    ADD CONSTRAINT fk_cvs_active_version
    FOREIGN KEY (id, active_version_id)
    REFERENCES cv_versions (cv_id, id)
    DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX ix_cvs_owner_status ON cvs (candidate_user_id, status, updated_at DESC);
CREATE INDEX ix_cv_versions_hash ON cv_versions (sha256);
CREATE INDEX ix_cv_versions_processing ON cv_versions (processing_status, updated_at);
