CREATE TABLE outbox_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL,
    aggregate_type VARCHAR(80) NOT NULL,
    aggregate_id UUID NOT NULL,
    aggregate_version BIGINT NOT NULL,
    event_type VARCHAR(120) NOT NULL,
    schema_version SMALLINT NOT NULL,
    idempotency_key VARCHAR(200) NOT NULL,
    correlation_id UUID NOT NULL,
    causation_id UUID,
    payload JSONB NOT NULL,
    headers JSONB NOT NULL DEFAULT '{}'::jsonb,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    available_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    published_at TIMESTAMPTZ,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    locked_by VARCHAR(120),
    locked_at TIMESTAMPTZ,
    last_error_code VARCHAR(80),
    last_error_at TIMESTAMPTZ,

    CONSTRAINT uk_outbox_events_public_id UNIQUE (public_id),
    CONSTRAINT uk_outbox_events_idempotency_key UNIQUE (idempotency_key),
    CONSTRAINT ck_outbox_events_aggregate_type_not_blank CHECK (char_length(btrim(aggregate_type)) > 0),
    CONSTRAINT ck_outbox_events_aggregate_version CHECK (aggregate_version >= 0),
    CONSTRAINT ck_outbox_events_event_type_not_blank CHECK (char_length(btrim(event_type)) > 0),
    CONSTRAINT ck_outbox_events_schema_version CHECK (schema_version > 0),
    CONSTRAINT ck_outbox_events_attempt_count CHECK (attempt_count >= 0),
    CONSTRAINT ck_outbox_events_lock_pair CHECK ((locked_at IS NULL AND locked_by IS NULL) OR
                                                  (locked_at IS NOT NULL AND locked_by IS NOT NULL)),
    CONSTRAINT ck_outbox_events_error_pair CHECK ((last_error_at IS NULL AND last_error_code IS NULL) OR
                                                   (last_error_at IS NOT NULL AND last_error_code IS NOT NULL)),
    CONSTRAINT ck_outbox_events_timestamps CHECK (
        available_at >= occurred_at
        AND (published_at IS NULL OR published_at >= occurred_at)
    )
);

CREATE INDEX ix_outbox_events_pending ON outbox_events (available_at, occurred_at)
    WHERE published_at IS NULL;
