CREATE TABLE recruiter_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    user_id UUID NOT NULL UNIQUE,
    display_name VARCHAR(160) NOT NULL,
    business_title VARCHAR(160),
    business_phone VARCHAR(32),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_recruiter_profiles_display_name CHECK (char_length(btrim(display_name)) > 0),
    CONSTRAINT ck_recruiter_profiles_version CHECK (version >= 0),
    CONSTRAINT ck_recruiter_profiles_timestamps CHECK (
        updated_at >= created_at AND (deleted_at IS NULL OR deleted_at >= created_at)
    )
);

CREATE TABLE companies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    legal_name VARCHAR(240) NOT NULL,
    display_name VARCHAR(240) NOT NULL,
    slug VARCHAR(160) NOT NULL UNIQUE,
    description TEXT,
    website_url VARCHAR(500),
    country_code CHAR(2) NOT NULL DEFAULT 'VN',
    registration_number VARCHAR(80),
    size_range VARCHAR(30),
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    verification_status VARCHAR(20) NOT NULL DEFAULT 'UNVERIFIED',
    created_by_user_id UUID NOT NULL,
    verification_reviewed_by_user_id UUID,
    verification_reviewed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_companies_registration UNIQUE (country_code, registration_number),
    CONSTRAINT ck_companies_names CHECK (
        char_length(btrim(legal_name)) > 0 AND char_length(btrim(display_name)) > 0
    ),
    CONSTRAINT ck_companies_slug CHECK (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
    CONSTRAINT ck_companies_country CHECK (country_code ~ '^[A-Z]{2}$'),
    CONSTRAINT ck_companies_status CHECK (status IN ('PENDING', 'ACTIVE', 'SUSPENDED', 'CLOSED')),
    CONSTRAINT ck_companies_verification CHECK (
        verification_status IN ('UNVERIFIED', 'PENDING', 'VERIFIED', 'REJECTED')
        AND (
            (verification_status IN ('UNVERIFIED', 'PENDING')
                AND verification_reviewed_by_user_id IS NULL
                AND verification_reviewed_at IS NULL)
            OR (verification_status IN ('VERIFIED', 'REJECTED')
                AND verification_reviewed_by_user_id IS NOT NULL
                AND verification_reviewed_at IS NOT NULL)
        )
    ),
    CONSTRAINT ck_companies_version CHECK (version >= 0),
    CONSTRAINT ck_companies_timestamps CHECK (updated_at >= created_at)
);

CREATE TABLE company_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    company_id BIGINT NOT NULL,
    user_id UUID NOT NULL,
    role VARCHAR(30) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    invited_by_user_id UUID,
    joined_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    left_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_company_members_company_user UNIQUE (company_id, user_id),
    CONSTRAINT fk_company_members_company FOREIGN KEY (company_id)
        REFERENCES companies (id) ON DELETE RESTRICT,
    CONSTRAINT ck_company_members_role CHECK (role IN ('OWNER', 'COMPANY_ADMIN', 'RECRUITER', 'VIEWER')),
    CONSTRAINT ck_company_members_status CHECK (status IN ('ACTIVE', 'SUSPENDED', 'LEFT')),
    CONSTRAINT ck_company_members_lifecycle CHECK (
        (status IN ('ACTIVE', 'SUSPENDED') AND joined_at IS NOT NULL AND left_at IS NULL)
        OR (status = 'LEFT' AND joined_at IS NOT NULL AND left_at IS NOT NULL AND left_at >= joined_at)
    ),
    CONSTRAINT ck_company_members_version CHECK (version >= 0),
    CONSTRAINT ck_company_members_timestamps CHECK (updated_at >= created_at)
);

CREATE INDEX ix_company_members_active_user
    ON company_members (user_id, company_id)
    WHERE status = 'ACTIVE';

