CREATE TABLE jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL,
    company_id BIGINT NOT NULL,
    created_by_user_id UUID NOT NULL,
    active_version_id BIGINT,
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    published_at TIMESTAMPTZ,
    closed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT uk_jobs_public_id UNIQUE (public_id),
    CONSTRAINT uk_jobs_id_company UNIQUE (id, company_id),
    CONSTRAINT fk_jobs_company FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE RESTRICT,
    CONSTRAINT ck_jobs_status CHECK (status IN ('DRAFT', 'PUBLISHED', 'CLOSED')),
    CONSTRAINT ck_jobs_lifecycle CHECK (
        (status = 'DRAFT' AND published_at IS NULL AND closed_at IS NULL)
        OR (status = 'PUBLISHED' AND published_at IS NOT NULL AND closed_at IS NULL)
        OR (status = 'CLOSED' AND published_at IS NOT NULL AND closed_at IS NOT NULL AND closed_at >= published_at)
    ),
    CONSTRAINT ck_jobs_version CHECK (version >= 0)
);

CREATE TABLE job_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL,
    job_id BIGINT NOT NULL,
    version_number INTEGER NOT NULL,
    title VARCHAR(240) NOT NULL,
    description TEXT NOT NULL,
    requirements_text TEXT NOT NULL,
    benefits_text TEXT,
    location_text VARCHAR(300),
    country_code CHAR(2),
    work_mode VARCHAR(20),
    employment_type VARCHAR(30),
    seniority_level VARCHAR(30),
    openings INTEGER NOT NULL DEFAULT 1,
    salary_min NUMERIC(19, 2),
    salary_max NUMERIC(19, 2),
    salary_currency CHAR(3),
    salary_period VARCHAR(20),
    salary_negotiable BOOLEAN NOT NULL DEFAULT FALSE,
    application_deadline TIMESTAMPTZ,
    source_hash CHAR(64) NOT NULL,
    created_by_user_id UUID NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_job_versions_public_id UNIQUE (public_id),
    CONSTRAINT uk_job_versions_job_number UNIQUE (job_id, version_number),
    CONSTRAINT uk_job_versions_job_id UNIQUE (job_id, id),
    CONSTRAINT fk_job_versions_job FOREIGN KEY (job_id) REFERENCES jobs (id) ON DELETE RESTRICT,
    CONSTRAINT ck_job_versions_number CHECK (version_number > 0),
    CONSTRAINT ck_job_versions_content CHECK (
        char_length(btrim(title)) > 0 AND char_length(btrim(description)) > 0
        AND char_length(btrim(requirements_text)) > 0
    ),
    CONSTRAINT ck_job_versions_country CHECK (country_code IS NULL OR country_code ~ '^[A-Z]{2}$'),
    CONSTRAINT ck_job_versions_work_mode CHECK (work_mode IS NULL OR work_mode IN ('ONSITE', 'HYBRID', 'REMOTE')),
    CONSTRAINT ck_job_versions_employment CHECK (
        employment_type IS NULL OR employment_type IN ('FULL_TIME', 'PART_TIME', 'CONTRACT', 'INTERNSHIP')
    ),
    CONSTRAINT ck_job_versions_openings CHECK (openings > 0),
    CONSTRAINT ck_job_versions_salary CHECK (
        (salary_min IS NULL OR salary_min >= 0) AND (salary_max IS NULL OR salary_max >= 0)
        AND (salary_min IS NULL OR salary_max IS NULL OR salary_min <= salary_max)
        AND ((salary_min IS NULL AND salary_max IS NULL)
            OR (salary_currency IS NOT NULL AND salary_currency ~ '^[A-Z]{3}$'
                AND salary_period IS NOT NULL AND salary_period IN ('HOUR', 'MONTH', 'YEAR')))
    ),
    CONSTRAINT ck_job_versions_source_hash CHECK (source_hash ~ '^[0-9a-f]{64}$')
);

ALTER TABLE jobs ADD CONSTRAINT fk_jobs_active_version
    FOREIGN KEY (id, active_version_id) REFERENCES job_versions (job_id, id)
    DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX ix_jobs_company_status ON jobs (company_id, status, published_at DESC);
CREATE INDEX ix_job_versions_deadline ON job_versions (application_deadline)
    WHERE application_deadline IS NOT NULL;
