CREATE TABLE applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL,
    candidate_user_id UUID NOT NULL,
    company_id BIGINT NOT NULL,
    cv_id BIGINT NOT NULL,
    cv_version_id BIGINT NOT NULL,
    job_id BIGINT NOT NULL,
    job_version_id BIGINT NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'SUBMITTED',
    source VARCHAR(20) NOT NULL DEFAULT 'DIRECT',
    applied_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT uk_applications_public_id UNIQUE (public_id),
    CONSTRAINT uk_applications_candidate_job UNIQUE (candidate_user_id, job_id),
    CONSTRAINT uk_applications_snapshot UNIQUE (id, candidate_user_id, company_id, cv_id, cv_version_id, job_id, job_version_id),
    CONSTRAINT fk_applications_company_job FOREIGN KEY (job_id, company_id)
        REFERENCES jobs (id, company_id) ON DELETE RESTRICT,
    CONSTRAINT fk_applications_job_version FOREIGN KEY (job_id, job_version_id)
        REFERENCES job_versions (job_id, id) ON DELETE RESTRICT,
    CONSTRAINT fk_applications_cv_version FOREIGN KEY (cv_id, cv_version_id)
        REFERENCES cv_versions (cv_id, id) ON DELETE RESTRICT,
    CONSTRAINT ck_applications_status CHECK (status IN ('SUBMITTED', 'UNDER_REVIEW', 'SHORTLISTED', 'REJECTED', 'WITHDRAWN')),
    CONSTRAINT ck_applications_source CHECK (source IN ('DIRECT', 'REFERRAL')),
    CONSTRAINT ck_applications_version CHECK (version >= 0),
    CONSTRAINT ck_applications_timestamps CHECK (updated_at >= applied_at)
);

CREATE INDEX ix_applications_job_status ON applications (job_id, status, applied_at DESC);
CREATE INDEX ix_applications_candidate ON applications (candidate_user_id, applied_at DESC);

CREATE TABLE application_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL,
    application_id BIGINT NOT NULL,
    from_status VARCHAR(30),
    to_status VARCHAR(30) NOT NULL,
    actor_user_id UUID NOT NULL,
    reason TEXT,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_application_status_history_public_id UNIQUE (public_id),
    CONSTRAINT fk_application_history_application FOREIGN KEY (application_id)
        REFERENCES applications (id) ON DELETE RESTRICT,
    CONSTRAINT ck_application_history_reason CHECK (
        to_status NOT IN ('REJECTED', 'WITHDRAWN') OR (reason IS NOT NULL AND char_length(btrim(reason)) > 0)
    )
);

CREATE INDEX ix_application_history_application_time ON application_status_history (application_id, occurred_at);
