CREATE TABLE job_processing_projections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id UUID NOT NULL,
    job_version_id UUID NOT NULL,
    source_hash CHAR(64) NOT NULL,
    status VARCHAR(20) NOT NULL,
    processing_task_id UUID NOT NULL,
    failure_code VARCHAR(80),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT uk_job_processing_projections_version UNIQUE (job_version_id),
    CONSTRAINT ck_job_processing_projections_status CHECK (status IN ('PARSED', 'FAILED', 'CONFIRMED')),
    CONSTRAINT ck_job_processing_projections_source_hash CHECK (source_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_job_processing_projections_failure CHECK (
        (status = 'FAILED' AND failure_code IS NOT NULL)
        OR (status <> 'FAILED' AND failure_code IS NULL)
    ),
    CONSTRAINT ck_job_processing_projections_version CHECK (version >= 0)
);

CREATE INDEX ix_job_processing_projections_job_status
    ON job_processing_projections (job_id, status, updated_at DESC);
