CREATE TABLE application_matching_projections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id UUID NOT NULL,
    cv_version_id UUID NOT NULL,
    job_version_id UUID NOT NULL,
    matching_result_id UUID NOT NULL,
    status VARCHAR(30) NOT NULL,
    final_score NUMERIC(5, 2) NOT NULL,
    quality_flags JSONB NOT NULL DEFAULT '[]'::jsonb,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT uk_application_matching_application UNIQUE (application_id),
    CONSTRAINT ck_application_matching_status CHECK (status IN ('COMPLETED', 'DEGRADED', 'INSUFFICIENT_DATA')),
    CONSTRAINT ck_application_matching_score CHECK (final_score >= 0 AND final_score <= 100),
    CONSTRAINT ck_application_matching_version CHECK (version >= 0)
);

CREATE INDEX ix_application_matching_score ON application_matching_projections (final_score DESC, updated_at DESC);
